{% set name = "vaex" %}
{% set version = "1.0.0b7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - pip
  run:
    - python
    - vaex-core
    - vaex-hdf5
    - vaex-viz
    - vaex-astro
    - vaex-server
    - vaex-distributed
    - vaex-jupyter
    - vaex-ui
    - healpy  # [(not win) and (py27 or py34 or py35)]
    - python.app  # [osx]

test:
  imports:
    - vaex
    - vaex.file

app:
  entry: vaex
  icon: logo.png
  summary: Lazy Out-of-core dataframes and visualization for large (~billion rows/objects) tabular datasets
  type: desk

about:
  home: https://vaex.io
  license: MIT
  license_family: MIT
  summary: 'Lazy Out-of-core dataframes and visualization for large (~billion rows/objects) tabular datasets'
  doc_url: http://docs.vaex.io

extra:
  recipe-maintainers:
    - maartenbreddels
