{% set name = "vaex" %}
{% set version = "2.0.0" %}
{% set sha256 = "b797e7a82954b5258d71dafe8541dca5206f0d87b10dac1580b42bcc9cd8b1c9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: 0
  noarch: python

requirements:
  build:
    - python
    - setuptools
    - pip
  run:
    - python
    - vaex-core ==0.7.2
    - vaex-viz ==0.3*
    - vaex-server ==0.2*
    - vaex-hdf5 ==0.4*
    - vaex-astro ==0.4*
    - vaex-arrow ==0.3*
    # - vaex-distributed
    # - vaex-jupyter
    # - vaex-ui

test:
  imports:
    - vaex
    - vaex.file

app:
  entry: vaex
  icon: logo.png
  summary: Lazy Out-of-core dataframes and visualization for large (~billion rows/objects) tabular datasets
  type: desk

about:
  home: https://vaex.io
  license: MIT
  license_family: MIT
  summary: 'Lazy Out-of-core dataframes and visualization for large (~billion rows/objects) tabular datasets'
  doc_url: https://docs.vaex.io

extra:
  recipe-maintainers:
    - maartenbreddels
