{% set name = "vaex" %}
{% set version = "2.2.0" %}
{% set sha256 = "b5e75dfc62d07c2662fd94c2be6912f1889a7330f03709990801d9b06929c161" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: 0
  noarch: python

requirements:
  build:
    - python
    - setuptools
    - pip
  run:
    - python
    - vaex-core >=1.0.0,<2
    - vaex-viz >=0.3.7,<0.4
    - vaex-server >=0.2.1,<0.3
    - vaex-hdf5 >=0.5.4,<0.6
    - vaex-astro >=0.6.1,<0.7
    - vaex-arrow >=0.3.5,<0.4
    # - vaex-distributed
    # - vaex-jupyter
    # - vaex-ui

test:
  imports:
    - vaex
    - vaex.file

app:
  entry: vaex
  icon: logo.png
  summary: Lazy Out-of-core dataframes and visualization for large (~billion rows/objects) tabular datasets
  type: desk

about:
  home: https://vaex.io
  license: MIT
  license_family: MIT
  summary: 'Lazy Out-of-core dataframes and visualization for large (~billion rows/objects) tabular datasets'
  doc_url: https://docs.vaex.io

extra:
  recipe-maintainers:
    - maartenbreddels
