{% set name = "vaex" %}
{% set version = "4.12.0" %}
{% set sha256 = "2d9ce86a383cf5e69ea9e0e164b598d5abf3f03a2777d6ccdb955f84c744d0e0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: 0
  noarch: python

requirements:
  build:
    - python >=3.6
    - setuptools
    - pip
  run:
    - python >=3.6
    - vaex-core <4.32.0,>=4.12.0
    - vaex-astro <0.10,>=0.9.1
    - vaex-hdf5 <0.13,>=0.12.3
    - vaex-viz <0.6,>=0.5.3
    - vaex-server <0.9,>=0.8.1
    - vaex-jupyter <0.9,>=0.8.0
    - vaex-ml <0.19,>=0.18.0
    # - vaex-distributed
    # - vaex-ui
    # - vaex-graphql

test:
  imports:
    - vaex
    - vaex.file

app:
  entry: vaex
  icon: logo.png
  summary: Lazy Out-of-core dataframes and visualization for large (~billion rows/objects) tabular datasets
  type: desk

about:
  home: https://vaex.io
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'Lazy Out-of-core dataframes and visualization for large (~billion rows/objects) tabular datasets'
  doc_url: https://vaex.io/docs

extra:
  recipe-maintainers:
    - maartenbreddels
