{% set name = "vaex" %}
{% set version = "4.14.0" %}
{% set sha256 = "71707d5d26a92484b64ea4dc19ea04925d374592128b072cd60336155ac6deb5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: 0
  noarch: python

requirements:
  build:
    - python >=3.6
    - setuptools
    - pip
  run:
    - python >=3.6
    - vaex-core <4.15.0,>=4.14.0
    - vaex-astro <0.10,>=0.9.2
    - vaex-hdf5 <0.14,>=0.13.0
    - vaex-viz <0.6,>=0.5.4
    - vaex-server <0.9,>=0.8.1
    - vaex-jupyter <0.9,>=0.8.0
    - vaex-ml <0.19,>=0.18.0
    # - vaex-distributed
    # - vaex-ui
    # - vaex-graphql

test:
  imports:
    - vaex
    - vaex.file

app:
  entry: vaex
  icon: logo.png
  summary: Lazy Out-of-core dataframes and visualization for large (~billion rows/objects) tabular datasets
  type: desk

about:
  home: https://vaex.io
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'Lazy Out-of-core dataframes and visualization for large (~billion rows/objects) tabular datasets'
  doc_url: https://vaex.io/docs

extra:
  recipe-maintainers:
    - maartenbreddels
    - JovanVeljanoski
