{% set name = "vaex" %}
{% set version = "2.0.1" %}
{% set sha256 = "83ab0c95c2c98455b3031a4d964390eec2f2df4d13ebec311400497962261b9f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: 0
  noarch: python

requirements:
  build:
    - python
    - setuptools
    - pip
  run:
    - python
    - vaex-core >=0.9.1,<0.10
    - vaex-viz >=0.3.4,<0.4
    - vaex-server >=0.2.1,<0.3
    - vaex-hdf5 >=0.5.2,<0.6
    - vaex-astro >=0.5.0,<0.6
    - vaex-arrow >=0.3.4,<0.4
    # - vaex-distributed
    # - vaex-jupyter
    # - vaex-ui

test:
  imports:
    - vaex
    - vaex.file

app:
  entry: vaex
  icon: logo.png
  summary: Lazy Out-of-core dataframes and visualization for large (~billion rows/objects) tabular datasets
  type: desk

about:
  home: https://vaex.io
  license: MIT
  license_family: MIT
  summary: 'Lazy Out-of-core dataframes and visualization for large (~billion rows/objects) tabular datasets'
  doc_url: https://docs.vaex.io

extra:
  recipe-maintainers:
    - maartenbreddels
