travis:
  secure:
    BINSTAR_TOKEN: 0iM+tv/yPuJQ+sry/sBvcDjLo+llZWC90D3I8jUNu2P1ymY8SfsEhW6ubuKzoblt8bBHBVaTcT/SPJtPKyVBBignN+0meT5UiDwgJuOkVlLJ2mUKDV628HWE6Js4TfNjGDuDQ0xOSScn089WBAbjBp2IljBw+ev3AfljAae2kV1X/sjBNJIy1hczJxc1qt6oHbjq+msEduGCdVUtS76vBRktyxPbx5GOI/0bAfq1rIk4uSpUa0ltFMveX5RU0UWyqih/kKAs/2y0elXkZi0T9mpPP7asDz6XYs7m14xj0zETgwlc3LIVKppJmKB73+oRfToV63WARCNW0AgP54cMQC54mGFTCAhXqfT6bikZS3I3NjkBIFkAwy8Pdaq4s/sBVZhRJf6ZBpRxDGsRUtPMo9QnytQD4NqXUaZCiLdfYm/66SFrflglGWvSKkylUXXGj38HPYPgGPpIGRLm1eHt7QmQNCwAPuL8A1iW/1oMTrcTSFcyR143xkMk1BTNiqsff40oUbNOowpzKe/eF4LZPgc+VESB4uHmryovaaNgCf2rgy7gItAPJBsidGQInR0iT5iMd6W3Pa0uMtzlZ8Ad/RY0bI3tjTU4tcTX9KtG5CWqb49pW+zb6usEitdtJXz/O9s+fl26yUGxZHfpX4CSNXd3tXXF325dJ1D6MfkGLmw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
