travis:
  secure:
    BINSTAR_TOKEN: eSLdDEHJwRsLeYJveytfh6G5/57m0Cc3KEQDapVFDsItxDPqDzaGyHYXzrkYcOq36Vl9umh25hC9y9W68Za3FwBKPVSgGxhUyJsTqhswwHKl2hEFvmjHRra4fWsZZCgoxIJrrhhvqaY+nhR/OVE+7O0nwkEinU18UVMGjW5YU6vp9ITOpEXMKqxY+VRPV8aMt0f/aSNTMFUbS66mJDSBy9TAoTyW+SlZtyrDKiHsWtXz38QzDYBqb4w4Xqg7xPz8SnePjAp67zzon8MKoQYWnFESGUI4P9u51R7aM+husvwlBJTC9mrjPIya5/5QmpP1oocGVs7PXYe34KqpOD2rjECjdQKZZGIKHcCpxSrWIbZXm53o3kUzp/xF2yoz5tBhRR4K/L65eX3Gk89/8mAm/+TwsbEAxSviMMtJjDUTuDUbeNihZp0EDpxLk4URgrqwVRVs4nbovZHnyMwx3iq2BPyG9vbNqeLWeOfp2noDvhGXlDPnzw1xFxZbxCx3gq67nNkZClLYQHB4qriu6rr74refo1DB0zGg0E4XacK3PlP4JPkcqPBqe5c5R7+74Q9wkXSY5nrR8dHkViXV/bEItPbCBB7FSkqXXm2JCAJYlt8G82FRmBF6XfKr30UBRG+dGjiwx3764Ol/S5von2Wqk9LPzgIbyEt9EtR4DIup5o4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
